# Generated by juwelier
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Juwelier::Tasks in Rakefile, and run 'rake gemspec'
# frozen_string_literal: true

# stub: activerecord_array_enum 0.0.0 ruby lib

Gem::Specification.new do |s|
  s.name    = 'activerecord_array_enum'
  s.version = '0.0.0'

  s.required_rubygems_version = Gem::Requirement.new('>= 0') if s.respond_to? :required_rubygems_version=
  s.require_paths             = ['lib']
  s.authors                   = ['Ryan Kerr']
  s.description               = 'TODO: longer description of your gem'
  s.email                     = 'leboshi@gmail.com'

  s.extra_rdoc_files = [
    'LICENSE.txt',
    'README.md'
  ]

  s.files = [
    '.document',
    '.rspec',
    '.rubocop.yml',
    '.ruby-gemset',
    '.ruby-version',
    'Appraisals',
    'Gemfile',
    'LICENSE.txt',
    'README.md',
    'Rakefile',
    'VERSION',
    'lib/activerecord_array_enum.rb'
  ]

  s.homepage                  = 'https://github.com/leboshi/activerecord_array_enum'
  s.licenses                  = ['MIT']
  s.required_ruby_version     = Gem::Requirement.new('>= 2.7')
  s.rubygems_version          = '3.3.7'
  s.summary                   = 'TODO: one-line summary of your gem'

  s.specification_version = 4 if s.respond_to? :specification_version

  if s.respond_to? :add_runtime_dependency
    s.add_development_dependency('appraisal', ['>= 0'])
    s.add_development_dependency('bundler', ['>= 1.0'])
    s.add_development_dependency('juwelier', ['~> 2.1.0'])
    s.add_development_dependency('rdoc', ['~> 3.12'])
    s.add_development_dependency('rspec', ['~> 3.5.0'])
    s.add_development_dependency('rubocop-rails', ['>= 0'])
    s.add_development_dependency('simplecov', ['>= 0'])
  else
    s.add_dependency('appraisal', ['>= 0'])
    s.add_dependency('bundler', ['>= 1.0'])
    s.add_dependency('juwelier', ['~> 2.1.0'])
    s.add_dependency('rdoc', ['~> 3.12'])
    s.add_dependency('rspec', ['~> 3.5.0'])
    s.add_dependency('rubocop-rails', ['>= 0'])
    s.add_dependency('simplecov', ['>= 0'])
  end

  s.metadata['rubygems_mfa_required'] = 'true'
end
